version: '2'

services:
  mysql:
    image: mariadb:latest
    #   hostname: mysql
    volumes:
      - ./db-data:/var/lib/mysql  # Persist storage
    expose:
      - "3306"
    environment:
      - HOSTNAME=mysql
      - MYSQL_ROOT_PASSWORD=sai@123
      - MYSQL_DATABASE=ghost
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=ghost@123 #please change this
    restart: always 
  ghost:
    image: ghost:latest
    hostname: ghost
    volumes:
      - ./ghost:/var/lib/ghost/content
    environment:
      - url=http://ghost
      - NODE_ENV=production
      - database__client=mysql
      - database__connection__host=mysql
      - database__connection__user=ghost
      - database__connection__password=ghost@123
      - database__connection__database=ghost
    expose:
      - 2368
    depends_on:
      - mysql
  nginx:
    image: nginx
    restart: always
    hostname: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./ghost:/var/www/html
      - ./ssl/private:/etc/ssl/certs
    ports:
      - 8080:80
    depends_on:
      - ghost

volumes:  
  ghost:
  nginx:
  db-data:
  ssl:

